- name: prep hosts for demo
  hosts: all
  tasks:
  - name: check for rhsm.conf.kat-backup
    stat:
      path: '/etc/rhsm/rhsm.conf.kat-backup'
    register: rhsmconf
    
  - name: Rename rhsm.conf
    command: mv "/etc/rhsm/rhsm.conf.kat-backup" "/etc/rhsm/rhsm.conf"
    when: rhsmconf.stat.exists == true

  - name: fix certs
    ansible.builtin.copy:
      src: /etc/pki/product-default/
      dest: /etc/pki/product/
      remote_src: yes

  - name: clean rhsm
    command: subscription-manager clean
      
  
