- name: run rhc system role
  hosts: all
  # vars:
  #   rhc_state: present
  #   rhc_auth:
  #     activation_keys:
  #       keys:
  #         -  "{{ activationkey }}"
  #   rhc_organization: "{{ orgid }}"
  #   rhc_insights:
  #     state: absent
  roles:
    - redhat.rhel_system_roles.rhc

- name: run journald system role
  hosts: all
  roles:
    - redhat.rhel_system_roles.journald

- name: run podman system role
  hosts: all
  roles:
    - redhat.rhel_system_roles.podman

- name: run cockpit system role
  hosts: all
  roles:
    - redhat.rhel_system_roles.cockpit
